import { useState } from 'react';
import type { CSSProperties } from 'react';
import { Loader2, Download, RefreshCw, Wand2, Eye, EyeOff } from 'lucide-react';
import { generateStory, SHARED_AI } from '../services/openai';
import type { StoryParams, StoryResult } from '../services/openai';
import { useStore } from '../store/useStore';
import { storyToPdf } from '../export/toPdf';
import type { DimensionKey } from '../data/dimensions';
import type { DimensionScore } from '../engine/scoring';

interface Props {
  scores: Record<DimensionKey, DimensionScore>;
  personaName: string;
  identitySentence: string;
  careerSuggestions: string[];
  coverImage?: string;
  story: StoryResult | null;
  onStory: (s: StoryResult | null) => void;
}

const SURPRISE = 'Surprise me';
const CUSTOM = 'Custom…';

const SETTINGS = [
  'A deep-space colony mission',
  'A dusty frontier in the Old West',
  'Present-day city life',
  'A high-fantasy kingdom',
  'A neon cyberpunk megacity',
  'A post-apocalyptic wasteland',
  'A Victorian-era mystery',
  'A pirate voyage on the high seas',
  'A 1940s noir detective city',
  'A solarpunk eco-utopia',
  SURPRISE,
  CUSTOM,
];

const TONES = ['Let the story decide', 'Hopeful', 'Heroic', 'Comedic', 'Melancholic', 'Adventurous', 'Mysterious', 'Cozy', 'Epic'];

const labelStyle: CSSProperties = {
  display: 'block', fontFamily: '"Cormorant Garamond", serif', fontWeight: 600, fontSize: 11,
  letterSpacing: '.1em', textTransform: 'uppercase', color: 'var(--ink-muted)', marginBottom: 6,
};

export function StoryStudio({ scores, personaName, identitySentence, careerSuggestions, coverImage, story, onStory }: Props) {
  const apiKey = useStore(s => s.apiKey);
  const setApiKey = useStore(s => s.setApiKey);
  const [showKey, setShowKey] = useState(false);

  const [settingChoice, setSettingChoice] = useState(SETTINGS[0]);
  const [customSetting, setCustomSetting] = useState('');
  const [profession, setProfession] = useState('');
  const [companion, setCompanion] = useState('');
  const [challenge, setChallenge] = useState('');
  const [tone, setTone] = useState(TONES[0]);
  const [length, setLength] = useState<'short' | 'medium'>('short');

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const resolvedSetting =
    settingChoice === CUSTOM ? (customSetting.trim() || 'a setting that fits the protagonist')
    : settingChoice === SURPRISE ? 'a setting of your choosing that best suits the protagonist — surprise the reader'
    : settingChoice;

  async function generate() {
    if (!apiKey.trim() && !SHARED_AI) { setError('Add your OpenAI API key to write a story.'); return; }
    setLoading(true);
    setError(null);
    try {
      const params: StoryParams = {
        setting: resolvedSetting,
        profession: profession.trim() || 'a profession that fits the protagonist — you choose',
        companion: companion.trim() || undefined,
        challenge: challenge.trim() || undefined,
        tone: tone === TONES[0] ? undefined : tone,
        length,
      };
      const result = await generateStory(apiKey.trim(), params, scores, personaName, identitySentence);
      onStory(result);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : 'Unknown error';
      setError(msg.includes('401') ? 'Invalid API key — check and try again.'
              : msg.includes('429') ? 'Rate limited — wait a moment and try again.'
              : msg.includes('quota') ? 'Quota exceeded on your OpenAI account.'
              : `Error: ${msg}`);
    } finally {
      setLoading(false);
    }
  }

  function download() {
    if (!story) return;
    storyToPdf({
      title: story.title,
      body: story.body,
      subtitle: `${personaName} · ${settingChoice === CUSTOM || settingChoice === SURPRISE ? resolvedSetting : settingChoice}`,
      footer: 'Generated by Selfscape — a fictional, for-fun short story inspired by your self-assessment. Not a factual account or clinical assessment.',
      coverImage: coverImage && coverImage.startsWith('data:') ? coverImage : undefined,
    }).catch(e => console.error('PDF export failed', e));
  }

  return (
    <section aria-label="Write your story">
      <div style={{ textAlign: 'center', marginBottom: 12 }}>
        <div className="kicker">Your own myth</div>
        <h2 style={{ fontSize: 34, margin: '6px 0 0' }}>Write Your Story</h2>
      </div>
      <p style={{ textAlign: 'center', fontSize: 14, color: 'var(--ink-muted)', maxWidth: 560, margin: '0 auto 22px', lineHeight: 1.6 }}>
        Cast yourself as the hero of an original short story. Choose a world and a role, add a few
        touches, and your character will live out the tendencies your answers revealed — then keep it as a PDF.
      </p>

      <div className="ss-card" style={{ padding: '24px 26px', display: 'flex', flexDirection: 'column', gap: 18 }}>
        <div>
          <label style={labelStyle}>Setting</label>
          <select className="ss-sel" value={settingChoice} onChange={e => setSettingChoice(e.target.value)}>
            {SETTINGS.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
          {settingChoice === CUSTOM && (
            <input className="ss-input" style={{ marginTop: 8 }} value={customSetting} onChange={e => setCustomSetting(e.target.value)} placeholder="Describe your world… e.g. a floating city above the clouds" />
          )}
        </div>

        <div>
          <label style={labelStyle}>Your role / profession <span style={{ fontWeight: 400, textTransform: 'none', letterSpacing: 0, color: 'var(--ink-faint)' }}>(leave blank to let the story choose)</span></label>
          <input className="ss-input" value={profession} onChange={e => setProfession(e.target.value)} placeholder="e.g. starship botanist, frontier sheriff, wandering bard" />
          {careerSuggestions.length > 0 && (
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 10 }}>
              {careerSuggestions.slice(0, 6).map(s => (
                <button key={s} type="button" onClick={() => setProfession(s)} className="ss-chip" style={{ cursor: 'pointer', color: 'var(--gold-deep)', borderColor: 'rgba(182,130,53,.4)' }}>{s}</button>
              ))}
            </div>
          )}
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(200px,1fr))', gap: 16 }}>
          <div>
            <label style={labelStyle}>A companion <span style={{ fontWeight: 400, textTransform: 'none', letterSpacing: 0, color: 'var(--ink-faint)' }}>(optional)</span></label>
            <input className="ss-input" value={companion} onChange={e => setCompanion(e.target.value)} placeholder="e.g. a wisecracking robot, a loyal wolfhound" />
          </div>
          <div>
            <label style={labelStyle}>A challenge or quest <span style={{ fontWeight: 400, textTransform: 'none', letterSpacing: 0, color: 'var(--ink-faint)' }}>(optional)</span></label>
            <input className="ss-input" value={challenge} onChange={e => setChallenge(e.target.value)} placeholder="e.g. a sabotage to uncover, a storm to survive" />
          </div>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(200px,1fr))', gap: 16 }}>
          <div>
            <label style={labelStyle}>Tone</label>
            <select className="ss-sel" value={tone} onChange={e => setTone(e.target.value)}>
              {TONES.map(t => <option key={t} value={t}>{t}</option>)}
            </select>
          </div>
          <div>
            <label style={labelStyle}>Length</label>
            <div style={{ display: 'flex', gap: 8 }}>
              {(['short', 'medium'] as const).map(l => (
                <button
                  key={l}
                  type="button"
                  onClick={() => setLength(l)}
                  aria-pressed={length === l}
                  className="font-display"
                  style={{
                    flex: 1, padding: '9px 0', borderRadius: 4, cursor: 'pointer', fontWeight: 600, fontSize: 15,
                    textTransform: 'capitalize', transition: 'all .15s',
                    border: `1px solid ${length === l ? 'var(--gold)' : 'rgba(32,31,29,.16)'}`,
                    color: length === l ? 'var(--gold-deep)' : 'var(--ink-muted)',
                    background: length === l ? 'rgba(182,130,53,.12)' : 'transparent',
                  }}
                >
                  {l}
                </button>
              ))}
            </div>
          </div>
        </div>

        {!apiKey.trim() && !SHARED_AI && (
          <div style={{ position: 'relative' }}>
            <input className="ss-input" type={showKey ? 'text' : 'password'} value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder="sk-... (your OpenAI API key)" style={{ paddingRight: 40 }} aria-label="OpenAI API key" />
            <button type="button" onClick={() => setShowKey(v => !v)} style={{ position: 'absolute', right: 12, top: '50%', transform: 'translateY(-50%)', color: 'var(--ink-faint)', background: 'none', border: 'none', cursor: 'pointer' }} aria-label={showKey ? 'Hide key' : 'Show key'}>
              {showKey ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
            </button>
          </div>
        )}

        {error && <p style={{ fontSize: 13, color: 'var(--no)' }}>{error}</p>}

        <button className="ss-cta ss-cta-primary" style={{ width: '100%' }} onClick={generate} disabled={loading}>
          {loading ? (<><Loader2 className="w-4 h-4 animate-spin" aria-hidden /> Writing your story…</>)
            : story ? (<><RefreshCw className="w-4 h-4" aria-hidden /> Write a new story</>)
            : (<><Wand2 className="w-4 h-4" aria-hidden /> Generate my story</>)}
        </button>
      </div>

      {story && !loading && (
        <article className="ss-card" style={{ padding: '32px 34px', marginTop: 16, borderColor: 'rgba(182,130,53,.3)' }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16, marginBottom: 18 }}>
            <h3 className="font-display" style={{ fontSize: 30, color: 'var(--ink)' }}>{story.title}</h3>
            <button className="ss-cta ss-cta-primary" style={{ fontSize: 13, padding: '8px 16px', flex: 'none' }} onClick={download}>
              <Download className="w-3.5 h-3.5" aria-hidden /> Download PDF
            </button>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16, color: 'var(--ink-2)', fontSize: 16, lineHeight: 1.7 }}>
            {story.body.split(/\n{2,}/).map((para, i) => <p key={i}>{para.trim()}</p>)}
          </div>
          <p style={{ marginTop: 22, fontSize: 12, color: 'var(--ink-faint-2)', fontStyle: 'italic' }}>
            A fictional story inspired by your answers — for enjoyment, not a factual account.
          </p>
        </article>
      )}
    </section>
  );
}
